on:
  # push:
  #   branches:
  #     - create_action
  create:
    tags:
      - v*
name: Build framework
jobs:
  static:
    name: Build static
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p frameworks/static
          xcodebuild -target AdjustStatic -configuration Release clean build
          zip AdjustSdk.framework.zip frameworks/static/AdjustSdk.framework/*
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: static_framework
          path: AdjustSdk.framework.zip
  tvOS:
    name: Build tvOS SDK
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Universal tvOS SDK
        run: |
          mkdir -p frameworks/static_tvos
          xcodebuild -configuration Release -target AdjustSdkTv -arch x86_64 -sdk appletvsimulator clean build
          xcodebuild -configuration Release -target AdjustSdkTv -arch arm64 -sdk appletvos build
          cp -Rv build/Release-appletvos/AdjustSdkTv.framework frameworks/static_tvos
          lipo -create -output frameworks/static_tvos/AdjustSdkTv.framework/AdjustSdkTv build/Release-appletvos/AdjustSdkTv.framework/AdjustSdkTv build/Release-appletvsimulator/AdjustSdkTv.framework/AdjustSdkTv
          zip AdjustSdkTv.framework.zip frameworks/static_tvos/AdjustSdkTv.framework/*
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: universal_tvos
          path: AdjustSdkTv.framework.zip

  dynamic_ios_tvos:
    name: Build dynamic iOS and tvOS targets with Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Carthage
        run: |
          brew install carthage
      - name: Build dynamic framework
        run: |
          mv Adjust.xcodeproj/xcshareddata/xcschemes/AdjustSdkIm.xcscheme \
            Adjust.xcodeproj/xcshareddata/xcschemes/AdjustSdkWebBridge.xcscheme .
          carthage build --no-skip-current
          zip AdjustSdkDynamic.framework.zip Carthage/Build/iOS/*
          zip AdjustSdkTv.framework.zip Carthage/Build/tvOS/*
      - name: Upload iOS
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_ios
          path: AdjustSdkDynamic.framework.zip
      # - name: Upload tvOS
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: dynamic_tvos
      #     path: AdjustSdkTv.framework.zip

  dynamic_imessage:
    name: Build dynamic iMessage target with Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Carthage
        run: |
          brew install carthage
      - name: Build dynamic framework
        run: |
          mv Adjust.xcodeproj/xcshareddata/xcschemes/AdjustSdk.xcscheme \
              Adjust.xcodeproj/xcshareddata/xcschemes/AdjustSdkTv.xcscheme .
          carthage build --no-skip-current
          zip AdjustSdkIm.framework.zip Carthage/Build/iOS/*
      - name: Upload framework
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_imessage
          path: AdjustSdkIm.framework.zip

  dynamic_webbridge:
    name: Build dynamic WebBridge target with Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Carthage
        run: |
          brew install carthage
      - name: Build dynamic framework
        run: |
          mv Adjust.xcodeproj/xcshareddata/xcschemes/AdjustSdkIm.xcscheme .
          carthage build --no-skip-current
          zip AdjustSdkWebBridge.framework.zip Carthage/Build/iOS/*
      - name: Upload framework
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_webbridge
          path: AdjustSdkWebBridge.framework.zip

  release:
    name: Create new release
    runs-on: ubuntu-latest
    needs: [static, tvOS, dynamic_ios_tvos, dynamic_imessage, dynamic_webbridge]
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ github.ref }}
          draft: true
          prerelease: false

  upload_assets:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Download all frameworks
      - uses: actions/download-artifact@v2
        with:
          path: frameworks
          
      - name: Upload static framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./frameworks/AdjustSdk.framework.zip
          asset_name: AdjustSdk.framework.zip
          asset_content_type: application/zip
          
      - name: Upload tvOS framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./frameworks/AdjustSdkTv.framework.zip
          asset_name: AdjustSdkTv.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic iOS framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./frameworks/AdjustSdkDynamic.framework.zip
          asset_name: AdjustSdkDynamic.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic iMessage framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./frameworks/AdjustSdkIm.framework.zip
          asset_name: AdjustSdkIm.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic WebBridge framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./frameworks/AdjustSdkWebBridge.framework.zip
          asset_name: AdjustSdkWebBridge.framework.zip
          asset_content_type: application/zip

